#!/bin/bash -ex

ADMIN_USER="administrator"
ADMIN_PASS="turnkey"
ADMIN_MAIL="admin@example.com"

DB_NAME=gnusocial
DB_USER=gnusocial
DB_PASS=$(mcookie)

WEBROOT=/var/www/gnusocial

# unpack tarball to webroot and set permissions
tar -zxf /usr/local/src/gnusocial.tar.gz -C /var/www/
rm -f /usr/local/src/gnusocial.tar.gz
mv /var/www/gnu-social-* /var/www/gnusocial

# fix missing dirs
mkdir -p /var/www/gnusocial/{avatar,background,file}

chown -R www-data:www-data $WEBROOT

# setup database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

/etc/init.d/mysql start
$MYSQL_ADMIN create $DB_NAME

$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update apache configuration
a2dissite 000-default
a2ensite gnusocial
a2enmod rewrite

# complete the installation
/etc/init.d/apache2 start
URL="http://127.0.0.1/install.php"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

curl --data "sitename=GNU+social&ssl=always&host=localhost&dbtype=mysql&database=$DB_NAME&dbusername=$DB_USER&dbpassword=$DB_PASS&admin_nickname=$ADMIN_USER&admin_password=$ADMIN_PASS&admin_password2=$ADMIN_PASS&admin_email=$EMAIL&admin_updates=false&site_profile=public&submit=Submit&fancy-enable=enable" $URL
### QVITTER  & 2FA INSTALL ###
git clone https://git.gnu.io/h2p/Qvitter $WEBROOT/plugins/Qvitter 
git clone https://github.com/mitchellurgero/TwoFactorAuth $WEBROOT/plugins/TwoFactorAuth
git clone https://gitgud.io/panjoozek413/qvitterplus $WEBROOT/plugins/QvitterPlus
### Work around for an error in original setup ###
sed -i '/127.0.0.1/d' $WEBROOT/config.php

### Add Qvitter to bottom to config ###
cat <<EOT >> $WEBROOT/config.php
addPlugin('Qvitter');
addPlugin('QvitterPlus');
\$config['site']['fancy'] = true;
\$config['site']['qvitter']['enabledbydefault'] = true;
\$config['site']['qvitter']['defaultbackgroundcolor'] = '#f4f4f4';
\$config['site']['qvitter']['defaultlinkcolor'] = '#0084B4';
\$config['site']['qvitter']['timebetweenpolling'] = 5000;
\$config['site']['qvitter']['urlshortenerapiurl'] = 'http://qttr.at/yourls-api.php';
\$config['site']['qvitter']['urlshortenersignature'] = 'b6afeec983';
\$config['site']['qvitter']['sitebackground'] = 'img/vagnsmossen.jpg';
\$config['site']['qvitter']['favicon_path'] = Plugin::staticPath('Qvitter', '').'img/gnusocial-favicons/';
\$config['site']['qvitter']['sprite'] = Plugin::staticPath('Qvitter', '').'img/sprite.png?v=40';
\$config['site']['qvitter']['enablewelcometext'] = true;
\$config['site']['qvitter']['customwelcometext']['en'] = '<h1>Welcome to GNUSocial!</h1><p>You can change this in the config.php file.</p>';
\$config['site']['qvitter']['blocked_ips'] = array();
\$config['thumbnail']['maxsize'] = 3000;
\$config['profile']['delete'] = false;
\$config['profile']['changenick'] = false;
\$config['public']['localonly'] = false;
\$config['db']['schemacheck'] = 'script';
addPlugin('StoreRemoteMedia');
addPlugin('TwoFactorAuth');
\$config['queue']['daemon'] = true;
\$config['queue']['enabled'] = true;
\$config['queue']['subsystem'] = 'stomp';
\$config['queue']['stomp_server'] = 'tcp://127.0.0.1:61613';
\$config['queue']['stomp_username'] = 'guest';
\$config['queue']['stomp_password'] = 'guest';
\$config['queue']['control_channel'] = 'gs-control';
\$config['queue']['queue_basename'] = 'gs-queue';
\$config['queue']['stomp_persistent'] = true;
\$config['queue']['stomp_transactions'] = true;
\$config['queue']['stomp_acks'] = true;
\$config['site']['qvitterplus']["custommenu"][0]["label"] = "TKL Home Page";
\$config['site']['qvitterplus']["custommenu"][0]["href"] = "https://turnkeylinux.org";
\$config['site']['qvitterplus']["custommenu"][0]["title"] = "TurnKey Linux Home Page";
\$config['site']['qvitterplus']["custommenu"][1]["label"] = "GNUSocial Home Page";
\$config['site']['qvitterplus']["custommenu"][1]["href"] = "https://gnu.io";
\$config['site']['qvitterplus']["custommenu"][1]["title"] = "GNUSocial Home Page";
\$config['site']['qvitterplus']['quotes'] = true;
\$config['site']['qvitterplus']['directm'] = false;
\$config['site']['qvitterplus']['trending'] = true;
\$config['site']['qvitterplus']['pinned'] = true;
\$config['site']['qvitterplus']['emojis'] = true;

EOT

## RUN CHECKSCHEMA (This will install any plugins that require extra tables in SQL.##
php $WEBROOT/scripts/checkschema.php


# delete confirmation mail to $ADMIN_MAIL
rm -f /var/spool/postfix/maildrop/*

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

### UFW Firewall

ufw disable && ufw --force enable
ufw allow 22
ufw allow 443
ufw allow 80

## Disable IPv6 in UFW for now
replace "IPV6=yes" "IPV6=no" -- /etc/default/ufw
ufw disable && ufw --force enable

### rabbitmq-server configuration-ish stuff.
rabbitmq-plugins enable rabbitmq_stomp
#systemctl restart rabbitmq-server

### Fix Stomp libs:

rm $WEBROOT/lib/stompqueuemanager.php
cp /var/www/temp/stompqueuemanager.php $WEBROOT/lib/stompqueuemanager.php
rm $WEBROOT/extlib/Stomp.php
cp /var/www/temp/Stomp.php $WEBROOT/extlib/Stomp.php

### Enable gnusocial.service

systemctl enable gnusocial.service

## Add packports for newer-ish packages on jessie.
echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/99backports.list
